
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 02 10:16:09 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 14;
  public static final int READ = 6;
  public static final int IDENT = 29;
  public static final int PLUS = 10;
  public static final int RBRACE = 25;
  public static final int RPAREN = 23;
  public static final int EQUAL = 15;
  public static final int SEMI = 19;
  public static final int GOTO = 9;
  public static final int RETURN = 7;
  public static final int LBRACE = 24;
  public static final int LPAREN = 22;
  public static final int COLON = 18;
  public static final int PROGRAM = 2;
  public static final int BOOLEAN = 31;
  public static final int INC = 16;
  public static final int COMMA = 20;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int CHARCONST = 30;
  public static final int DIV = 13;
  public static final int DEC = 17;
  public static final int LSQUARE = 26;
  public static final int MINUS = 11;
  public static final int DOT = 21;
  public static final int CONST = 3;
  public static final int PRINT = 5;
  public static final int error = 1;
  public static final int RSQUARE = 27;
  public static final int NEW = 4;
  public static final int MUL = 12;
  public static final int VOID = 8;
}

